name: rick_and_morty_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2


dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/characters.png
    - assets/images/locations.png
    - assets/images/episodes.png
    - assets/images/wallpaper.png

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icon/app_icon.png"
